"""packaging/sync_version.py — single source of truth for the installer's
version (V0.8.6).

The desktop client's version lives in exactly one place:
`CLIENT_VERSION` in client/uploader/uploader.py (it's also what the
client reports to the server for the minimum-version check). This script
READS it — by regex, without importing the client, so it works before any
dependencies are installed — and writes packaging/version.iss, the
one-line include that packaging/garage16.iss pulls in. Running it before
every installer build makes it impossible for the installer to advertise
a different version than the app inside it.

Usage:  python packaging/sync_version.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parent.parent
UPLOADER = ROOT / "client" / "uploader" / "uploader.py"
VERSION_ISS = ROOT / "packaging" / "version.iss"

_VERSION_RE = re.compile(r'^CLIENT_VERSION\s*=\s*"(\d+\.\d+\.\d+)"\s*$', re.MULTILINE)


def read_client_version(source: Optional[Path] = None) -> str:
    source = source or UPLOADER  # resolved at call time, not bound at import
    match = _VERSION_RE.search(source.read_text(encoding="utf-8"))
    if not match:
        raise SystemExit(f"Could not find a CLIENT_VERSION = \"x.y.z\" line in {source}")
    return match.group(1)


def render_version_iss(version: str) -> str:
    return f'; GENERATED by packaging/sync_version.py — do not edit by hand.\n#define AppVersion "{version}"\n'


def main() -> int:
    version = read_client_version()
    VERSION_ISS.write_text(render_version_iss(version), encoding="utf-8")
    print(f"Installer version set to {version}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
